using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdventOfCode2024
{
    internal class Day4 : IDay
    {
        public string input => "MMSAXXMMMMSMSMXMXSSMAMSMSXMASMMAXMASMMSMMAMXXMASXMXXXMSASXSSMMXSAMXXMAXXSMSMSMXXAMXAXMMMSMXAMMASMSMXAMXXMMMMSMSXSAAMXMMMSAMXSMMMMMSAMMSMSXXX\r\nMASMMSMMAMMAMMASXMXXAMXMSXAAXAXAMXMXMASXXASXSSSMXXMAMAASXXSAMXASASASXSSMMASAAMSMSMSXSAAAAMMMSMMMMAMSASMMMMXAAXXAXMMSAMMSAMXAAMASAMMASAAMSMMS\r\nMMSMASMSAMMAMSMSAASMMSAMSMMXXMMXXASXSXXASXSAASAMXAAAMMSAMXSXMMMSAMASMAAXMAXMAMSAAMAAMMMSASAAAAXASMMAAMMAXAMMSSMXMMASASXSAMMSMSAXAXSAMMMSXMAA\r\nXSXMXSASASXMMMASMMMAXXAMXAXMXSAMSXSASMXMSSMMMXMSSSSXSMMASASASAMMAMSMMSMMMMSSMAMSMMXSSMMMMAMMSSMASXMMXMXXMSSXAAAAMMAMSMXSAMAAAMMSSMMASAMSAMSS\r\nMMMSMMAMAMXAAXXXMXMXMMMMSMMAMMAMXAMAMXSXMAXAMAXXAAXMAXSAMASASMSSSMAAXMAAAAAAMXMXSXAMXAXSXSMMAMMAMAXXXMSMAAXXMMSXSAASXMASAMSXSSMXAASAMMMSAMMX\r\nMAAAAMAMXMSMMXMASMXXMASXSAMSASMMSAMXMAMMSMMXSMSMMMMXMMMSMMMMMMXAMXSMMXXSMSXXMASXMMAXSMMSXMAMMSMXSAMXAAMMMMSMXAXASMSAMXMSMMMAMXXSMMMXSXMMXMAS\r\nSMMXMXASAMASAAMAMAXMSMXASMMMMSAMXMMXMASAAAMMAMAXXAMMSAAXXXAMSXMXMXMAAMMXXMXMSASAXSXMASAXAMMMXAMMSXMXSSSXXXXAMMSMXMAXMSXSAAMAMAAXXSXMMAMXAMAS\r\nAMSSMXMXMMAMSSMAXSAMXSMAMAASXSMSAMXASASXSAMSASMSSXMAXMSSSSSMAAMXMMSAMAAMMSAMAMSMMMMAXMMSAMSASASAXASAMXAXSMMXMXMXASAMXSASMMMAMXSMMSAMSAMMXMAS\r\nSAAAMMSSMMAMAMXMMXAMAXMXMSXSAMXSMXSASASAMMXSASMXAXAMXSAMAAAMSAMSXAMAMXMAASASMAXXXXASXAXMXXSASAMXXAMAMMMAASMMSAXMAMASAMAMAMXSMMAXAMMMMAMXAXAM\r\nAMSSMXAAASMMMMSMAMAMASXSMMMMAMAXMXSAMXMMXSAMXMMSMMSMMMASMXMAMAAXMSXMSSXMMSAMXAMMMSAXMMMSMXMAMAXMASXMMAXMMMXASXSXMSXMAMXMAMAMAMSMXSXMSAASMMAS\r\nXMAMAMMMMMAMXAAMSSSMAAAASAAMMMSXMAMAMXSAAXAXXMASXAAAASAMXAAASMMXXMASAMAXMMMXMXSAAXMMAAAAAXAASXMMAMAASMSSXXMXSMSAASMMXMSSSSMSAMAAASAMXSMSAMXA\r\nAMMXXMSAMXMMMSMSAAXMASXMSXSMSAXASMSMMAMMSSMMSMASXSXSMSXSMXMMXMSMSMMMASXMXAMMMASMSMASMMSSMMMAMXAMXSMMMAAMMXMSMASMMMAMAXMAAAXXASMSMSAMAAXMASMS\r\nXMSMSAMMSSXAAMMMMSMMXMXXXMXXMASAMXAXMAXMXAXAXAAXAMAMXMASAAMXMASAMMMSAMXSSMMAMMSAXXAMAXXAASXMSSXMMMMSMMMSAAMAMXMAAAXSAMMMMMXMMMAAXSMMSSMMAMAM\r\nXAAAMAXSAMSXSMASAAMSAMMSMMMAMAMMMMMXSASXSMMXSMXMXMAMAMSMSXSASMMSMAXMMMAMMMSXMASMXMMSSMMMMMAAAXMXMAAXASASMMSASXSSMSAMAXXXASAAASXSXMAMAAAMAMAM\r\nSAMXMMMMMMMMMMAMXSMSXSAAAXSXMXAMXMSAMXSAAXAMMASMXMXMSMMAAXXXSXAAXXSASMXSAAMXMASXMAXAAXAAAMMMMSMSMMMSAMXSAMXMMAAXAMASAMXMASXSXMXXASMMXSAMXMAS\r\nXXXMAAAXMAXAXMMMAMXMMMXSSMXXXXSAMXMASMMXMMSSMAMMAAMMXAMMMSMASMSSSMSAMMAMMXSAMASMMSMMSSXSMSAMXAAAAMAAXAAMXMASMSSMXMXMAMSAMXMMMMSSMMAAXMMSASAA\r\nXXSXSSSXSASXMSAAXXSXAAAXMASXMXMAMXSAMAMAXMXMMXSSXMXAXXMXAAMXMAXMAXMAMMSXSASXSAMXAAAMAMXAMXMSSSSSSMXMAMXXAMXSAAMAXMAMSXSAMMAXAAAAXSMMXSASXSMM\r\nAMXAMXXAMXXXAMXSMAMMMSSMXSMASASASXMMSASXSXXMAMMMAAMMSMMASXSXMSASXMSMMAAAXAMMSXMMSMSMASMMMAAXXAAAAAXAXMMSSSMMMMMSMXMXXASMMXMMMMSXMMAMXMASXMMX\r\nMSAXMAMSMSMMMMAXMAMXAAAAMASAMASAMMAXSASAMAMMMAASMMSAAAMXMAMMMMMMAMXSMXMMMAMAMAMAXAMMMMMXMMXXMMSMMSMSMAAXXAXAAMMMMSMMMAMAMXXASMMXSSMMAMXMXMAA\r\nXSAXMXMAAXXAXAAXSXSMMSSMAXMXSMMXMSMMMMMAMSAMXXXSXAMXSMSASAMMXSASAMAXXAAXSMMSSMMAXAMXMAMMMMMSMAAXXXAAXMMSSSMMMMAAMAMAMAMAMXSXSAMXMAAXMAMSASAS\r\nXSAASAMMXMSMSMMXMAMAXXMASXAASAMMAAAMXMSMMMSSXSSMMMSAMXMASXMXMSASMSSSMSSMXMAXAXMMSSMMXASAAAAAMMSXMMSMMSMMAMMSXXXMSASXSXSAMXSMMXMAXSMXXMMAAAXX\r\nMMAMMAMXXMXMAAMAMSMSSMSXMMMMSAMXSXSMXXSAMXAXMXAASAXAXXMAMASMAMMMXAXAAAAMSMMSXMAMAXXMSASXSMSMSAXAXAXXASAMXMAAMXSASASAMXXXXMMAXMSSXMSMMMSMMMMX\r\nAMXMMAMSMMASMMSAMMAMXAMMXXSXSXMMXXAXXAMXAMXXMXSMMAMSMSMXSAMASXMMMMSXMSXMMAXMASXMASXMAAMAXXAXMASMMSSMMXXMAMMXSAAMXMMASMMMMMSSMXAMXAASAAAXXAXM\r\nXSASMSXMASAMSASXMMAMMAMSMXMMSASASXXMXMSMSSMMSAMXSAMAAAAMMXXXXXMASMSXAMAMSSMSAMMMASXMMSMAMMMSMAAXAXXMSXSMXXAAMMMAXXXAMAAAAMAMXMASMMMXMXSXXMSS\r\nXMAXAAXSMMMMSMMAMSXMXAAAASAASAMAXAASXAAMAAAMSASAMASMSMSMMMSSMXSASASMXMAMSMAMASMMASAXAXMAXAXAMMMMXMAMXASASMMSMXMSMSASXSMSMSASXMASAMSMSXMAASAX\r\nASAMXMASXMMASAMSMAASXSMXSMMXMMMXMSAMMXMMSMMMMMMXMAMAXAMASAXAAAMAMAMAXSMMXSAMSMMXAMAMMMMMSMXMXXXXAMAMMAMAMXMAMXAXAASMXXXXXMXMXXAMAMAAMAMSMMAS\r\nMXMSXXXMAXMASAMXMMXSAXXMMAXAMSSMXMAASXSAXAAMAMXMASMXXASMMMSMMMMXMAMMMMAMAXXXXMSMSSSMAAXXAXAAMXMMXXAMSAMXMASMSSSSSMMXXMXMAMMXMASXXSMXMSMAXMMM\r\nMAMXXMMSSMMMSMSXMXMMAMSSSMMMSMAXXXAMXAMMSSMSASAMMAAMMMMAAAAXAMXMMXSXASAMSMXMMAAAXAMMMMSAAMSXSAASXSMXSMXMXMASAAAAAXSMMXSAAMSAMXMAMXXAMXMMXMAS\r\nSASAMXAAAXXXMASMXAMMSMAAAXMXAMMMMSSMMXMXAXMSXSAMXMSXSSSSMSSXXMAXXAAXAXXMAXMMMSMMMMMMSASMSMAASMMMAAXASASMSSMMMSMXMASASAMSMSMXSMSXSASMSASXMSAS\r\nSMSASMMSSMMXMSMMSXSAAMMSMMSSMSXXAAAMXXXMASAMMSAMXXXAMXMXMAMXMSASMSMMSXMSMSAXMASXAXAXMASAMXMXMSMMMMMXXAASAAASXMXMMXSAMMXAXAAAMAMAMASASMSAXMXM\r\nMAXAMXMMXMMMMAAAXAMMXMMXAAMAMXXMXSSMXXMMXSXMASAMMMMMMSMSMSSMMAAAAXXAXXXAMAAXSASMMMXSMMMMMSXAAMXSAXSXMMMMXSMMXSAMXAMAMMSSMMSMMAMSMAMAMAMMMXAM\r\nSXMAMXXMAMSAMSMMMAMAASXMMXXAMXMAMMXAMMXSAMXXAXMMAAAAXMAMAAAAXMMMXMMXSXSAMXAMMXSAMXMXAAAAAXXMSMASXSMAXSASXMASXSASMMXAMXAMAXAMSMSXAXMXMXMAMMXM\r\nXMAXXMAXMSMXXAMXMSMSMSAMASMAMXASASXSAAAMASAMXSASXSSSXMAMMSSMMXMXAMMMSASMMMSXSXSAMSMSMSSSXMXXXMASXAMMMMASMMAMXSAMXMAXSMASXMXXXMAMXSMMMASAMAAA\r\nMASASMMSMAMSSMSAAAAXASXMAMAAAMXMSMAXMMXSAMAXAAXMAXAXASMXMXMAASMSXXAAMAMMAMXAXXSXMAXAMMMXAXMAMSXMMAMSMMAMXMASXXAMMSXSAMAMAASMSXSSXSAASASASXSS\r\nASMAXMAAMMXMAMSMSMSMMSAMXSSMSAAMAMMMASAMXSXMXSMMXSASXMXAXAXXXAASAMMSMSSSMSMAMMMMSSSMXSASXMSAMXAMXXAAAMASXMAMXXAXXAXSAMASMMMAXMASAMSMMASAMAAX\r\nSAMXMMSMSSSMMMXMAMAAASAMMXMAXMXSAMASAMMAMXAXSAMXAMAMMASXMSSSSMAMAASXMMAAAXXAMXAAXMAMAMXMMMMMSMSMASXMXMAMXMMXSMMMMMXMMSMXAAMAMSAMMMXSMMMXMSMS\r\nXXSXXAXSMAAAASXSMSSSMMASMMMMMSAMXSXMAMSAASMMXAMMMXSMXAMMAXXAAXMMXMXASMSMMMSMMSMSSXXMXSAMAAAXAAAXXXAXXMXMSXSASAAMAMAAXMASMMMSAMAXXXXAXMASMAAA\r\nMASMMMSAMSMMMAAAAXAMXSAAMAAAAAMAAMMSAMSXMSASXSMSMAXMMXXMMXMXAMXXMMSAMAXAXAMXXAMAMASMMSASXSSSMSMSMSMMXSAAXAMAXAXSMMMSMMAAASAMXSSMSMSMMXAXSMSM\r\nMAMXAMXMXMASMMSMMMSMMMMSSMMSSMXMXSAAXXXMASAMXAAXMASASAXXSMSAMSAMMMMMXSMXMASMSMMXSASAMSXMAAAAAAAXAAMMASMSMMMSMMMMXSXXAMXSMMMSMMMAAAAXMXMXMXXX\r\nMSSSSSSXMXMXAXXXXAAXAAMAMXMAXXASAMXSXSMSMMMMSMMMAAMAMXSAAAAXSMMXSAMXXXXAMMAAMMMMMASXMXASAMXMMMSMSMSMASAXXXAXAXMAXMASXMAXAAMXMAMSMSSMSAMAASMS\r\nAXAMXAAAAAMSSMMXMSMSSSMSMSMAXXAMMMXXAMAAXMSAAAMMSXMXMAMMMMMSMAMAMXXAAMSXSSSXMAAAMXMXXXAMAXMASXMAAAMMMMMMAMSMMXMAMAMXAMASXMSASAMXMAMXSASMXSAX\r\nXMXMMSMMMMXXAAXMAAXXAMXAASMSMSSMSMAMAMSMSAMSSSMAAASAXAAAMMXMMAMMSSMMXAASXAAAMMSMMASASMSSSMAAAAMMMSMMXAAXSAMXSMSSMXMSAMMSMASMSSMMMXSXSAMXAXMX\r\nMXXXAAXSXSMSAMXAXMXMMMMMMMAXAAAAAMXMAMXAMXMMMAMMSXMASMSSMSAMSXSXAAAAMMXSMMMMMXAMSAXMXAAAMMSAMXXXXXAMSSSMASMAXAAAAAAXASMMMAMASAMXXAXASXSMMMSS\r\nASMMSMSAASAMMSMSAXSSMSASMMSMMMMSMSAMMAMXMASASXMAXAMAXMAMAMMXAMXMMSMMSSXMASXXXAAMMMMXMAMAMAAXSAMSASMMAXMMAMXSMMMSMAMSAMXAMSSMSAMXSMMMMMMASAAX\r\nXAAMASMMXMAMAMAMMXAAAXAXAAAXAXXAAMXMAAXASXSASXMASAMXSMXMAMSXMMMAXXAXAAASAMMSAMMMAXAAMAMXMAMAMXMSAMMMXSMMMSSMASAXXAMMMMXXMAXXXAMAMAAAAXSAMMSM\r\nSSXMMMMXMMMMMSMAXSMMMMSMMSSSSSSSSMASMSMMXMMAMXMMXXXMAMXMSXMASMASXMSMSSXMXSXSASMSMSXSSXXAMMASMSAMAMXXAMAAMSXSAMXXMMSXAASXXMASMMMMSSSXSMMMSAXX\r\nAXAXXXSAMSAMXMXMASASAMXAXMAAXAXXAMXSAAAMAAMAMXSAAMMMAXMAXASAXASXMAMAMMMSMMASXMAAAXAXMMMAMXAXAXASAMMMXMMMXMAMXXSXSAXXMXMXAMAXAAMMMAAAMMSSMASX\r\nMSMMXXMAMAAMMMMMASMMMMSAMMMMMMMSMMMMMMASXSAASXAMSMAXSMMXMAMASMAXAMMAMXAAAMAMAMSMXMXMAAXAMMMSASXMXAXSXSASXMXXSASASAXSMSSXXMSSSMMAMMMMMAMAMMMX\r\nMAASXSSMMSSMXAAMASXXAAMXMXAMXXMSSMASXXXMAMMMMMXMAXMMMXMSSSMXMMAMSXSAMMSSSMSSXMAMXSAMXMSMSAMMMMAASXMAMSAMXMAMXAMAMMMSAAMXSXMAXMMMSAXSMMMAMAXM\r\nMAXAAAXSAXAXSSMMMSXXMXMAMXMXSAMXAMSMMSMSAMXAXXAASMSAMAMXAAMXXXMSAASMSAAAMAAXMSASASASAXAXMXSXSSMMMMMAXMMMMMASMXMXMASMMMMAXAMMMSAMXMSXAMXAMSXS\r\nMSXMMMMMMSMMMXMSSMXSAMMSMAXSXAASXMASAAXXASMMXSAMMASXSASMMMMMSMSAMMMSAXMXMXMAXSASASASXXXMAAAMXAMSSXSXSAAAXSASXAMASXSMSSMMMXMAAXASXMAXSMSMSMAA\r\nSMAMASXXAAAAXAAXAAMMAMAXSMXSAMXXXSASMMSXMMAMAMMAMAMASASASXSXAMXAXAXAMMXMAMXMAMAMXMAMAXSSMSSMSAMXSAXXXXSSMMASMMSASXMXAAAAMSAMMSMMMMAXMAAXAMMM\r\nMXMMASMXSMSXSASXMMMSXMAMAMASXMMMXMAXMXSAMSAMAXAASXSMMAMXAAXMMMAMXMXSXMAMAMAMMXASAMAMXMMAAAMMSAMXMXMASMXMAMAMXXAXXAMMSMMMMAAXXAXAAMMSMSMSMSMS\r\nSMAMASMAMMMMMAMXXMMSXMMSSMASAAAMAMSMMASAASASXSSMSAAXMXMXMAMAASAMMSAMXSASASXSXMASASXXMAXMMMSAXXXASXAAAMASXMMSAMXSSMMAMXSASXMMSSSSXSAAXAMAAAAM\r\nAMAMSXMAMAAAMMMMMSMMAMAAMMXSMSXMXSAAMASAMSAMAAMXMAMAXXMSXAASXSASAMASMSXSASAMAMASMMAAAMMXAAMAXMMXMASXXMASXXXSASAMAMMMMASAMAMXXAAAAXXMMXXMSMSM\r\nMXMXAMSSSSSMSAXAAAAAAMMMSMXMMMMSMSMSMXXXAMXMMMXXMAXAAMAMSMXAAMXMXSAMXXMMAMASXMASAMMMMMAAMMSSXXAXSXXMXMASMMMSAMXSMSMXMXMSMMXSMMMMMMMSASXMMAMX\r\nXASXSXSAMMAMXAMMSSXMXXXXSXAXAAXAASAMMMMMMSSXXXMSSMMSMAAXAXMMXMASXSMSMMASMSAMAMXXAMSXSAXXXXAMMSSMSASMAMASXAAMXMASXAMAMMAXMSAXAXAMXAAMMSAAXMAX\r\nMXSAAXMAMMSMMXXMAMMMXMAMMSMSSMSASMAMMAMAMAMXMMAMAMXMMSSSMSXSASXSASAAXMAAAMMSSMSSSMSAXMASMMMSAMXAMAMXAMMMMSSMXMASXXMASMAMAMASXMMASMMAAMMMMXMS\r\nXAMMMXSMMAAAMXAMAXSSMSXAXAMAAMXMXMXMXSMAMASASMMSAMSSMAXAXXAXASAMMMSMXMMSXSXMAAMAMAMXMXMMAASAMMMSMAMSXSAMXMAAAMMSXXSASMXMXMXMMASAXASMXMMXAAMA\r\nMAMXXMMAMAXAMSXMASAAAMSXMASMMMAMMSMMXMMAMMXASAAMMMAAMASXSMSMAMAMAAMMXXAMMSASMMMXMXMAAAMSSMSAMXAXXXMAASMMAXMMMXAXAMXASAMMXMXAAAMMSXAASXSXSSXM\r\nMMSXMASAMSSSXXXMMAXMMMSMSMMAMSXSAAASAMSMSAMSMMMSMMSXMMMMAAAMXMSSMXSASMXMXSAMXSXSMSSMMXMAXMMMMSSSMMMMMMASMMSAASMSSXSAXAAMASXSMXSAMXMMMXAAXXMX\r\nXAAAMXXXXMAMXXXXMASXSXMAAXMXMAAMXMXMAMAAMMMXAXAXXXMAXAAAMSMSSXMAXAXXMMMSMMXMSAAAAAAMASMMSSXSXXAAXXAXASAMXASMXMAAAASAMSSSMSAMXMMXSAXXSMSMMAAS\r\nMSSSMSSMMMXMSAMXMASXAAMSMSSSMSSMSXASXMSSSMSSSMSSXAXXSSMMXMAAMMSAMXSMAXAAXSMXXMSMMMXMAXASXXAAMMXMMMXSAMMSMXSXAMSMMMMSMAAAXSAMSXMASXSAAAMXMXMX\r\nXXAMAAAMASAAXXMMSAMXSSMMXAAMAMAMXMMSAAAAAXAAXAXXXMAXXXASMMMMXXXMXMAXAAMXSMXMMMXAXMSMSSXMMMSMXSAAAAXMXMAAMXSXAXXMASXMMSSSMSAMXXMXSAMMMMMASXMM\r\nMMMMMMMSAXMSMMMAMAXAMMAXMMSMXMXSAMXSMMMSMMMSMMMMMMSXAXXAXMXSXMXMSMSAMXSSMMAMMXSSXMAMMAMXMAXXASMSMSMMXMSMSAXXMMSMASMXAXAAMXAMXSMAMXMAMAMMSAAA\r\nXAXMXXMMMXAAAAMSSSMMSSSMAMXASMXMMXMXMAXAXSXMXXAXAAMMMMAMXXAMAMAMAAXMAMMAXSAMXXMAASXSMMMSMXMMAMXMAXMSMAMAMMSMSAAMXXAMMMSMMXSMSMMASMXXMXAAMAMX\r\nSMMSAMXAMSSMMMSAAXAMXAAXMMMXAMAAMMSAMAMAMSAMAAXSMXSAAMSXSMASAMAMMXMXMASAMSASXMMSMMAAAASXXMASMMMMMSASMXMAMXXAASXXMXXXXAXXSAMXSAMASXAMMMMSSSSM\r\nAMAAASMMMAMAAXMMXMSMSXMXSXAXAMSSMASAMSMSASAMMMMMMXMXXSMAMMMMAXXSMMSAXAMAMMAMMAAMAMXMMMSAXMXMAAXSXMASMSSSSXMSMMXASMXMMMSAMXMMSAMASMXSAAAXMAAM\r\nMSSSMSASMAXMMMXSXAAXAAXXAAMMSXMAMASMMXAAASAMAAAASXMSMSMXMASMSMMSAAAMMSSXMMMMMXMSXSASAXMAMSASMXMAAMAMAAAXAXMMXMMAMAASXMMXMXMXXAMMSAASMMMSMSMM\r\nMAXXAMAMMMMSMSAASMMXSAMSMSXAMASXMXMMAMXMXMASMXSSMMAAASMASAMAMMXMMMXMAXMMMMSSXMXXMAAAXSAMXMASAXASMMSSMMSMMMAMAMMMSMXMAMAMXAASXSMAMXMXMMXXAMSM\r\nMASXMMSMXMMSAAXMMMAXAAXAXAMAXAMASMSXSMSAMSAMXXMAMMXMXMAAMXSSXMXMAMAMSMMASAAXSXSAMMSMXMASXMMMMMAMAXMAMXXAXMAMAXAMMXASAMASASMSAMMAXAXAMSMMMMAS\r\nMSMXXAXAMXAMXMMMASMMSSMMAMSSMASAMXXMASAAMMMMMMMAMXSSSSMMSMAMASMXSMXXMASASMSMMMMAMMAXMSAMASMAMMXMXSXSXSASMSMSMSXSMMMMAMXXAXXMAMXSSMSMSAMAMSAS\r\nSAMXMXXAMMMXMAAXAXAMAXXXAXAASAMAMXASXMMXMASMSMSMMMMMAAXXXAASAMXAXAMXSAMAMMAAASXSMSMMXMMSAMMSMAASXMMXAXAXAXAAAXMSASXSSMSMSMASMMMAAAAXSMMAXMAS\r\nSMSXMAXAMAMASASMSSMMSSMSMSSMMMSAMXXMXMASMMMAAAAMMAAMMMMMSMXMASMXSMSXMAMAMSSSMXAXASXMASAMXSAMMSASAMAMSMMMMMSMSMAXAMMMMAMAAXAMXAXSMMMXMAXMXMXM\r\nSAAMXMASMMSASAXAMXXXAMXMXMAXXMMAMMMMMSASAMMMMXMSSMXSAAAXAMSSMMMXAASMMAMAXAMXXMXMASAXSXMXXMASMXXSAMMAXAMXXAXMXXSMMMMAMAMSMSMMSSMMSSMXXMASMMMM\r\nMAMAXMXMAXMMMAMAMMMMMSAMASXMMSSMMAMAAMASAMSMXXXXXXASXMASMSMAXAXMMXMAMSSSSSXAXMMMXMAXXAMAMMXMAMASXMXSSSMMMMSXSAMXMASXSMXAAAAMAAAAAXXMSXAMAXMM\r\nSXMXXMAMMMAMMSMAXAMAXSASAXAAXAAASASMMSASMMMMMMSAMMXMXSAMXAXMMXSXXAMAMXAAAAMMSMAXXXXSMSMAAAAMAMAMXMXMAMXMASMAMAMXSASMAMSMSMSMSSMMSSMAXMXSAMXM\r\nSAXMASXSXSSMAXMXSSSMXSMMMXSMMMSMXAMAXMXMAASAAAMAMMMSMMMSSXSXXXMXSMSASMMMMMMAAXMSSMASXASMMXSSMSSMMSSMAMXMSMMAMMMMMASXMASAMAAAXXMAXMASMXMXMASX\r\nSAMSAMXXAMAMXSMMXMAMMXXASMMXSMMXMXSMXAMSXMSMMMSAMXAMMASAXXSAMXAAMMMMSXXXAAMXSSMAAMAMXMMSSXMMAAMXMAAXAMSMAXXMXXAXMXMXMSMAMSMSMSMSSSSXAAMSASXM\r\nMMMMAXAMSXSMAMAMXXAXXAMASAMMSASXSAAXMAXSAXXMXMMMSMSSSXMASMSAMMMMMAAMXXMSSSSMAMMSMMSSXAAAMAAMMMXXMASXMSXXAXMSSSMSSXMXXXXSMXAXAXMAMXAMSMSSXMAX\r\nSASMSMSMMAAMXMAMMSMXXAMASAMMMAMAMMXMASAMXMASXAAAAXXAMXMXMASXSXSSSSSSXAXXXAAMMSAAXSAMXMMSSMMXXMMMAAXMXSMSSSMAAAMAMAMSMSXXMMSMMMMSSMMMXMAMASXM\r\nSASAXAXAMXMAXSAAAAMSMSSXSXMAMAMSMSMXXAMXSMASXSMSXMSASXSAMMMAMMMAXMAMMMMMMSMMSMMSXMASAMXAXAMSMAAXAAXMASAAAAMMSMMAXXXSAMMSXMXASMMASAAAXMAMMAMX\r\nMAMMMXMXMXXAMSSMMXSAAMSAXXSSSMSAAAXXMXMASMMXXXXXXXXAMAXXMAXAMXMMMMAMASAAMAMMMAMMMSXMAMMMXSMAXSASXMXMASMMXMMXAXMMSMMMAMAMAMSAMXMAXXMMMMMSMSSS\r\nMAMXMXXAMMAXXMXSAMSMSMMMMAMMAXSMSMSXMAMMSASMMSXSASMAMAMSSMSXSXMXAXMSSXMXXASAMMMAASMSXMAMXAXXXMXAAMMSXSMXAAXSMMAMAMASXMMSAMSASAMXSSSSXSMAMAMM\r\nSAXSAMMMAAAMMMAXMAXAXXSASXSSXMXXXXMAXSSXSAMAXMAMAMSMMXSAAMSASAAXSSMMMAAMSMMXSAMMMSAMXSASMSAMXSMMAMAXXXAMSMMASMASASMXSAASAMXAMXSXAAAMAXSAMASA\r\nXMAXAMAMXXSAAMSSMSMAMXXASAAXMASMSMMMSASAMXXXMMAMXMAMSMMXSAMMSAMAMXMMSXMXAMMMSXSMMMXMASASAMSXAMXASMXSMMXMAASAMSAMXMMMMMMSAMMSMASMMMMMMMSXSASX\r\nMXSXMMSMSAAXSAAXXXMAMSMMMMMMXXAAXAASAMXMMSSXSSMSXSAXMAMAMAMXXAMAMASASMMSXSAMXAMAXXMSASAMXXMMMMSSMAASXMASXMMMXMXSMAMAAMXMAMXAMASXAASAMASMMAXM\r\nSMMAXSAAMAMMMMSSMXMAXSMMASASASMMMSMSAMXSAAAAMMMSXMMMMAMXMAMMSXSASAMXXAXAAXMASMSAMXAXAMMMXMXAAASAMMMXAXAXMSSMSMMMAAXXSXMMMMSAMXMMSASAMASAXSMM\r\nMASXMMMMSAMXXAAAMSMSXMASASMSASXAAXXSAMAMMSMMMMAMAMASMMMSAAMAMAMXMMSMMSMMSMXMAAMAMMMMSMSAXAXSSMMMMMMSSMSSMAXMAMAMMMSAAXSASXSXXAXAMMSAMXXXAMAX\r\nMAMMMXAAXXSXAMXMAXAMMAXMXSASAMMMSSXSAMXSAMASAMASAMASAAAMXMMASAXXMASAAAAMXXAMMSMAXAMAAAMMXXMAAXSXSSXAXAXAMMSSMMASAAMMSMSASAMAXSSSMASXSAMASXMM\r\nMAMAMSMSSMMMMXSMMMMMAXAXXMXMAMXAMXASMXMMMSXMASASXSASXMMSAMSXSMXXMAXMMMSXXSXMAMMXSSSSMSMSAMMSMMAAXXMSSMSSMXMAXSAMAMXAXXMXMAMXMXAMMMSAAMAAAAAM\r\nSMSMXAAAXAXMSAXASAMASXXXASASMMMMXMXMMAAMAXXAMXASMMASMMASAMAMXAASMMSXAMXMAMAMMSXMXXAXMAAMASAXXXMMMSXAAMAMXAMXMASMSXMASMMASXMSMMAMMXMMMMMAXXMM\r\nAAAMMMMMXXMASASXMSMAXMMMMXMMMXMAAMMSSSSSXAMMXMXSAMAMASASMMMMMMXXAASMSXASXSAMMAMMMMXMSSXSAMXSMMXAAXMSSMMSSMSMMMAMXAMMMASASMAAMMMSMAMASAMXMSMX\r\nMMMXSSSSXMSASMSAAXMAMXAAAASMSMMSXSAMAMAAXMMAXSMSXMMSMMASAXMASMMMMMMAXSMMAXMMMXAAAMAXXAAAMXXMASXMASAMXMAMAMAAAAAXMXMMMXMMMMXMSAXAXASMSMMMSAAX\r\nMASXSAASAAMASASMMMXMASASMMSAAAXAAXMMAMXMMMASXSAMMSXXMMMMMXMASAASMSMSMAMMMMSAMMSSSSSSMMSMMSMSXMAXAAMMAMSMAXMMMMMMXAMAXXSMSMSMSASMSMMAMXSMXMAS\r\nSASXMMMMMMMSMAMXMAAXXSAXAAMMMMMMSMSSSMSMSXAMAMAMAMMMSASASMMASMMMAAXAXMMXMASASAAAMAAAAAAXXAAXXMXMMSSSXMAXAMMMSSMMSMSMSXMAAAAMXMAMSMSXSASASXSA\r\nMXSXMASAAXXAMXMAMSMSAMASMMMAXXMSAMMAMMXAAMXSAMMMMMAXMAMMXAXMMXMMSMSMSXAAMXSAMMSSMSMSMSSSSMSMXSAXXAXAASMSMXXAAAXXAAAASAMSMSMSMMMAMAAAMASAMSXM\r\nMMMASAMSXSMMMASAXAAAAMXMXXXMMSMSAXMAMXMAMSXXAMXAXSSSMSMSSSMMASMAXXAXAMSMMXMMXXMAAXAAAXXAMXMMAMXSMMSMMMMAMXXMSSMSMSMSMAMMAXAAXSMMMSMXMAMAMMSX\r\nSASXMAMXMXAXSASMSMMSMMMSMMSXSMXSAMSSSSMSXXAXSXSXXAMXXXAXAMAMAMMASXMSMMASXMMMSMMMAMSMSMMMMAMXMASAXXAMSXSASMSMXAASAMMMXXMMXMSMXSAXAXXXMAXMMAMX\r\nAXAMMSAXMSSMMASAMXAAAAAAAMAXAAXXSAAAAXAXSMMMMAMMSMXSAMXMXMAMASMXSAAAMMASXAXAAAMXXXMAMASXMMSAXMMSXMXSAASAMAAXAMMMSMAAXMAXAAXMASXMASXSSMSXMAXX\r\nMXMXAMAAXMAAMAMMMMSSSMSSSXMSMSMMMMMSMMSMXMMAMXSAMXAAMASMMMSSMSMAXXMMSMAMMSMSSSMMXSXASAMAXASAXSAMMASXMXMSMSMSMSAXMSMMMAAMSSMMAXXXXMAMAAAXSSMA\r\nAXXMXSXMXAMMMMSAMXMAXAXAMMXAAAAXAMMMXSAMXMMXSMMMSMXSAMAAAAXAMXMMSMAAXMAMMXAMXAAAASMMMMSAMMSAAMAMASAXXAAAMXMXMAMSAAMASXXXXAAMMXXAXMMMMMMMSAMX\r\nXSAMXMXSXSXAXMSASMSSMMSAXAMMMMMXAMAXXXMSMSAAXAXASXAAASMMMMXAMXAXAXXXXSXSXSXXSSMMXXAXAAXAXXMXMXMMSMXXMMSMSAAXASMXXMSMSAMSSSMMSAMSMMMMXMXMSSMX\r\nSMMSSMAMAAMXSAMXMMAAMAMAMSSSSSMSMSMSMMXSMMMSSMMMSMMSMMXXXXSMSSSXXMMSAMXMAMAMMMMMMMSMMSSMMXAXMSSMAMMXMAMXSXMMXMASMXSAMAMAAAAAMAMMAAAXAXMXMMSM\r\nXAAAAMXXSAAAMAXSXMSMMSMMMAAMASAAMAMSMMAXAAAMAXAXXAXXXXXSMMAAAAMSSXAASAAMAMMMAAMAXXAAXMAMMMMMXAAMAMSAMMSMMAMXAXSAMAXAMXMMSMMSSSMSSMSSMXSAAMAM\r\nMMMSXMAMMMSMMAMMAXAXAMAMMMSMAMMMSAMMAMXSSMSXXXXXXMSXMAXAASMMMSMAMMSMASXSASAMXMSASMSSMMMAXAAAMXSMXMSASMAXXAMSAXXAMSMSXSMAXMXMAMXMXMAMAASMXMAX\r\nSXMXXMASAAXXMASXMMSMMMMMMSAMASMXSXMSAMMMMAMXSMSSSMAMAMSXMMAMAXMASAAXMMMAAMMMSAMASAXMXAASXSSSXXAXXXSAMMASMSXMXXXAMAAXAAMMXSAMAMMMSMMSMMXXSSSS\r\nAMSAMXMSMSXXAAXAMMAASMMAMXASASMAMAMMXMAMMSMMAAAAXXAASXMMMMXMSXSASXMAXMAMXMAXMAMXMXMMMSSMAMAAXSSMMXMASMXSXMASMMSMMMSMXMAAASASMMMAMXXSXSXMMAAX\r\nMSXSXSXMAAXSMSSSMMSAMXMASMXMAMMAMAAMXSAXXAAMMMMMMSMSASXXSAXAAXXXMAMMMMMSMMSMSAMXMXSXAXAMXMMMMMAAAXXMAMAMMSMMXAAASXMMSMMMXSXMAAMXMSXMASMXMMMM\r\nXSAMXMAMSMMMAXAMXXAAXXXASMSMSMMXXMSAAXMXSXMMXAAMXMMAAXMASMSMXXMXSAMXAMASAXAAXXSXSASMMSMMXMASASMMMMSMSMMSAAMMMASXMAXAMXASMMMSMAXSAMMMAMMSMSXA\r\nXMASAMAMAASMMMSSMXMSMSMASAAAMMSSXAXMMMXMSAASMMXSMAXMXMAAXMAMMSAXMAXMAMASAMMSMAXAXAMAXSXMXMXSXMAXMASAMXSMMSSXAMMAMXMMMMXSAAMMSAXMAMXMASXAAAMS\r\nMSASXSSMSAMAAAAAASAAAMMMMXMSMAAXMMMXASMASXMMAMASMMMMSASMMMASMASASASXSMXXAMAAMXMSMXMAMSAXMSAMXSSMMXMMMSXAMMMXSMXSMXSXASMSMMSMMSMSAMXSASMMSMMA\r\nMMASAXAAXSMSMSMSAMXMSMMAMSMXMMMSAMXSASMAMAMXXMASAXAAAAMAXSAAAMMMSAMAAAXSMMXSXAAXAXSXMMSMAMXSXAMASAMAMXMMMASMAMAXAAXXMMASXMXMAMMSASAMASAMMXSM\r\nXMAMXMMSMXXAAXXMASXXXMSMXAAMMAMXAXAAAMMMSAMSMMXSMMMXSSSXMASMXXAAMAMSMMMSAXAMAMMMMMSAMXMMMSAXMMSAMXMAMXMXSAXMAMSSMSSMMMAMASAMXSASMMAAASAMXAAX\r\nSMASAAAAXXXMSMXMAMMXMAAMXSSSSSSSSMSMXMAMMXSAASAMXXMXMAXXAMXXXXMXSXMXASASAMSXMMAAAXMAMASAMXMXXAMASAAMSASXMASMMSAAXAAXXMMSXMASAMXSXSXMXSMMMSMX\r\nXSASXSMSXSXMAXAMSMMASXMSAAAAAAAXMAMXSSMSAXMMSMMSMXMAMSMMSAMXMASAMXMXAMASAMMAASXSSSSMMXSMMMMSMMSAMXXSAMXAXASXMAMXMSSMMSAXXXAMXSXSAMAAAMASAAXA\r\nMMMMAMXMAMXSXMXMXASAXXAMXSMMSMSMXMMMAXMMMSXXAAXXMAMMXAASAMXXMAXAMXSMAMAMXMMAMSAAAAMMMAMAAAAAAXAXMAMAAASXMXXAMXAXMAAXAXASMSSXXXMMAMMMMSAMMSSX\r\nSSXSASAMAMAMXSMASAMASMSMXXXXXAMASMSMMSASAXMSSSMSSSSSXSMMMSMMMSMXAAAMXMXSXMASXMMMMMMAXXSSSSSSSMSMMASXMMSASXSMMMAXMXSMXSXMAAAASMSSXXXSAMASMMXX\r\nSAAXAAMMXMASXAAAMAMXAAAXMMSSMXMSXXAAXAASMAMAXAMAAMAMAMXMAAXMAMXSMASXSAMXASAMXXAXMASASAAXAMAAAXAASASMSAXXMMAMXXMAMSAAXMMMMMMMAAXXMSSMXMAMXAMX\r\nMMMMSMMASXMMMXSXSXMXMSMMAAAMAMXMASMMMMXMXXMAXMMMMMAMASAMSSSMAMAMXXXXMAMSMMSSMXSASASAMMSMMSMSMMSMMASAMMSMMXMSSMMAXMASXMXSAAXSMSMAXMAMAMSSMASM\r\nSAMMXAMSMAMSMMMMMMMAMAMXMAMXXMAXXMMSSXSSSSXSSXXMXSXSASAMMAMMSMSMAAMMMSMAMAMMMMAMXAMXMAXMAXMAXAXXMMMXMAAXAAAAAAMXSASAXAASXXMXXMXMMXAMAMMAMAAX\r\nSASXSAMMSAMAAAASAAMAMXSAMSMSMSXSAMXAXMXAAAAXAMXSAXAMXSXMMAMAMAMAXSAAAAMAXAXAAXMMMSMMMSMMMSXXMASAMXSAMSMSSSSSSMMAMXMAMMMSAMXSAMMSASMSSMSSMMSA\r\nSAMXSAMAMMSMSSMSMSSSSSMXSAAAASMMAMMMSSMMMMXMAMSMASMMMMMMSMMAMXMAMMXXMMXSSSSSXSASAAAMAMASXMMXXXSAMXSAXMXXAXMAMAMXSAMAMXMXXASAMXAAXAAAXXMMMMXM\r\nMAMMSMMMSMMXAAAMAAAASMAXSMSMSXAMAXAMAXXSXXAMAMXAMMMXAAAAAXMAMAMSMXSMMSMMAXAAAMAMXXXMXMAMAASMSXSAMASXMMXMMMSASMXAXASASMSAMMXMMMSSMMMMSAMAAMAX\r\nSAMMMMAXAXXMSMMMMMSMMMMMSAMXXXMSXSXMASMAMSXSXXXMMAXSSSXSMSMSSXSAMXXAAAAMSMMMMMSMSSSMSMASMSMMXASMMAMAMXSAXAMXSAXSSXMXSAMAMXAAXAAXXXAXMAXSSSSS\r\nSMXMASXSMSAXAAAMAAXXXXAXXXAMXAXAXAXMAXXAMMMAXSSMSXMXAMXAXMAMMXSASMSSMSMMAAAXXAMAXXAAXSXMMAAMMMMXMAXAMMXSMSXMMMMAAXMMXMSSMSSSMMSSXMASMAMXAMAS\r\nXMASXSXXMAMSSSMSMSSMXSMXSAMXMMSMXSAMMXMXAAXAMMAAAXMMAMSMMMAMMMSAMMAAAXMSSSMSMAMXMSMMMAMXSSXMAAXXSSSXSAMMMMAAAMMMMSMAXXAAMAAMXXAMMXMXMMXSAMAM\r\nSSMSAXMAMAXAXAMMAAXXAMAAMAAMAXXAAXAMXASMSXMSXSMMMXMMMMXMASASXASAMMMMMMAAAAAXXAAAXAMXAMAMMAASXSSMAAXMMMAAASXMMXXXASMSSMSSMMSMXMSMMASMSAAAXMAM\r\nMXAMXMAMSSSMSSMMXMMMSSMMSASMSMMMMSAMMMSAAAAXASXMXAMASMASXSXSMMSAMXMXMMMMSMMMSXSMSAMXSXSSMSMMAAMMSMSMSSMMXMAMSMSMXSAMSXAAXXAMSMXASASAMMSMXSAS\r\nXMXSMXSAMXAXAXAAXMMAAAXMAMXXAAXSASAMMXMAMAAMXMAMSMSAMSXSMSAXAMSMMASAAMXMAAAAMMMXSAMSXAAMAAAMMMMAAXMAASASMSSMAMAMXMAMMMXXMSAMXASXMMSMXXXXXAAA\r\nXAMAAXMAMSAMMSXMAXMSSMMMMXMSSSMMXMXMMXMSXMASMSAMXMMMXSMXASXSXMXAMASMMMAXMMMASMSASAMXMMMMSMSAMXMASMMMMSXSAAXXASAXAXAMXSSSXSSXMMMASXMXSXMMMMMM\r\nAMAMSMSAMXXAXMMSAMXMAMMAXAMAAMMSAMAMXAXMXSAMASAMMXSSXSAMMMXMASXSMXSAXSASXMSAAAMXSAMXAMAMXAMAMXXAXAXMXSAMMMMXMSASMXSAMAAMAMAMSXMAMAMAXASAXAAX\r\nMMAMXMASXMAMAMXSXAASAMSXSMSMSMAMAMASXMXMMMAMMMAXMAXMASXMAAAXMSAMXXMAMXAXAAMMMMMMSMMSSSMSMMMMSAMXSSMSAMAMXXSAMMXMAAAAAMMMXMMSMSMAMAMXSXMASASM\r\nASASXSAXMAMSASASMXMMMXXXAAAAAMSMSMXSASASAXMMMSXMMMSMAMASXMSSMMAMAMMSSMXMMMMSXMAAMAAAXAAXXMAXXASXMAAMAXMXMAXASASMMSMSXXXSMSXAAMXXMAMXMMSXXMAM\r\nMSAXAMMAMAASMMAMAXSXSMSMSSMSMXMAMAMXASASMSMAAXMAAMAMMSXMXXAMXMMMXXAAXXAAXXXXASXSXMMSSMMMMSMSXSAMXMSMSSMSSSSXMASAAAAMMMMSAMSMSMASXMASMAXMMSXX\r\nXMAMSMMAMMXXAMMMSMMAAAXAAXMAMAXAXXAMAMAMXAMMMSXSASMSXMAMMASMMASAMMMSSMSAMXMXMMMMAMXXMASMXAAXMAXXAXXAMXAAAAXMMXMMSMSMAAXMSMXXXMASAMASMSXXASMM\r\nSMXMMASMSMXXXMXAMAMXMXMSMMXASMSSMMSAAMAMXAMXXAAXMMMSASXMAXAASAMASAAXAMXMSMSMMAAMAMMMMAMXXMSMMXSXAAMMMMMMMMMMXMAXAMXMSMMXMMMSXMMSMMASMXAMXSAS\r\nXXSASMMAAASMSMMXSAMMSAMXXMMMSXSAAXMSMSXSMMMSAMMAXAAMXMASXMMXMASAMMSSSMAXAAAMSMMSAMSAMSSSMXXAMAMMMMAAAXAAXXMAAXMMMSSMMSMMXMASAMAMMMMSASXSASMM\r\nSMMXMMMMMSMAASAASAMXAASAAAXAMXXMMMXAMXAXXAAXAAXXSMMSAMXMASXASMMMAXAAASASMSMMAAXSAMMASXAAXAXXMASAXXXSASXSSMMSXSAXSAAAAAXSSMASAMXSAASMAMAMASMX\r\nXXMASXASXXMSMMMXSAMXSXMXXSMXSAXXMXSMSMXMMMSSSMAAMAXSAXASAASMMXMASAMSMMMSAXXSMSMSSMSXMMSMMMSXSMSMSXMXMMMAXXMAXSAMMSSMMXSAAMMSMMSSMSSMXMXMAMAS";

        public string example => "MMMSXXMASM\r\nMSAMXMSMSA\r\nAMXSXMAAMM\r\nMSAMASMSMX\r\nXMASAMXAMM\r\nXXAMMXXAMA\r\nSMSMSASXSS\r\nSAXAMASAAA\r\nMAMMMXMMMM\r\nMXMXAXMASX";


        string[] ParseData(string input)
        {
            return input.Split("\r\n");
        }


        public string Run(bool UseInput = true)
        {
            string[] data = UseInput ? ParseData(input) : ParseData(example);

            int output = 0;

            for (int y = 0; y < data.Length; y++)
            {
                for(int x = 0; x < data[y].Length; x++)
                {
                    if(data[y][x] == 'X')
                    {
                        output += CheckedAmount(x, y, ref data);
                    }
                }
            }


            return output.ToString();
        }

        int CheckedAmount(int x, int y, ref string[] input) 
        {
            int output = 0;

            if (CheckForward(x, y, ref input)) output++;
            if (CheckBackWards(x, y,ref input)) output++;
            if (CheckUp(x, y, ref input)) output++;
            if (CheckDow(x, y, ref input)) output++;
            if (CheckLD(x, y, ref input)) output++;
            if (CheckLU(x, y, ref input)) output++;
            if (CheckRD(x, y, ref input)) output++;
            if (CheckRU(x, y, ref input)) output++;
            return output;

        }



        bool CheckForward(int x, int y, ref string[] input)
        {
            if(input[y].Length-x <= 3) return false;
            if (input[y][x + 1] != 'M') return false;
            if (input[y][x + 2] != 'A') return false;
            if (input[y][x + 3] != 'S') return false;
            return true;
        }

        bool CheckBackWards(int x, int y, ref string[] input) 
        {
            if (x < 3) return false;
            if (input[y][x - 1] != 'M') return false;
            if (input[y][x - 2] != 'A') return false;
            if (input[y][x - 3] != 'S') return false;
            return true;
        }
        bool CheckUp(int x, int y, ref string[] input) 
        {
            if (y < 3) return false;
            if (input[y-1][x] != 'M') return false;
            if (input[y-2][x] != 'A') return false;
            if (input[y-3][x] != 'S') return false;
            return true;
        }
        bool CheckDow(int x, int y, ref string[] input) 
        {
            if (input.Length - y <= 3) return false;
            if (input[y+1][x] != 'M') return false;
            if (input[y+2][x] != 'A') return false;
            if (input[y+3][x] != 'S') return false;
            return true;
        }
        bool CheckRD(int x, int y, ref string[] input) 
        {
            if (input.Length - y <= 3 || input[y].Length - x < 3) return false;
            if (input[y + 1][x + 1] != 'M') return false;
            if (input[y + 2][x + 2] != 'A') return false;
            if (input[y + 3][x + 3] != 'S') return false;
            return true;
        }
        bool CheckRU(int  x, int y, ref string[] input) 
        {
            if (y < 3 || input[y].Length - x <= 3) return false;
            if (input[y - 1][x + 1] != 'M') return false;
            if (input[y - 2][x + 2] != 'A') return false;
            if (input[y - 3][x + 3] != 'S') return false;
            return true;
        }
        bool CheckLD(int x, int y, ref string[] input) 
        {
            if (input.Length - y <= 3 || x < 3) return false;
            if (input[y + 1][x - 1] != 'M') return false;
            if (input[y + 2][x - 2] != 'A') return false;
            if (input[y + 3][x - 3] != 'S') return false;
            return true;
        }
        bool CheckLU(int x, int y, ref string[] input) {
            if (y < 3 || x < 3) return false;
            if (input[y - 1][x-1] != 'M') return false;
            if (input[y - 2][x-2] != 'A') return false;
            if (input[y - 3][x-3] != 'S') return false;
            return true;
        }

        bool CheckX(int x, int y, ref string[] input)
        {
            return (input[y - 1][x - 1] == 'M' && input[y + 1][x + 1] == 'S' || input[y - 1][x - 1] == 'S' && input[y + 1][x + 1] == 'M') &&
                   (input[y - 1][x + 1] == 'M' && input[y + 1][x - 1] == 'S' || input[y - 1][x + 1] == 'S' && input[y + 1][x - 1] == 'M');
        }

        public string Run2(bool UseInput = true)
        {
            string[] data = UseInput ? ParseData(input) : ParseData(example);

            int output = 0;

            for (int y = 1; y < data.Length-1; y++)
            {
                for (int x = 1; x < data[y].Length-1; x++)
                {
                    if (data[y][x] == 'A' && CheckX(x,y,ref data))
                    {
                        output++;
                    }
                }
            }


            return output.ToString();
        }
    }
}
